package aplicativo_colegio_claretiano;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author Luis Daniel
 */
public class BusquedaEquipos extends javax.swing.JFrame {
private ArrayList<Equipo> listaBuscados = new ArrayList<>();
DefaultTableModel modeloTabla;

    public BusquedaEquipos() {
        initComponents();
        modeloTabla = (DefaultTableModel) tblResultados.getModel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        L_logo = new javax.swing.JLabel();
        L_información = new javax.swing.JLabel();
        txtValorBusqueda = new javax.swing.JTextField();
        L_buscar = new javax.swing.JLabel();
        cbCriterioBusqueda = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        L_buscarEquipos = new javax.swing.JLabel();
        lblMensajeBusqueda = new javax.swing.JLabel();
        btnMenu1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 40, 74));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        L_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N

        L_información.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_información.setForeground(new java.awt.Color(255, 255, 255));
        L_información.setText("Ingrese información:");

        txtValorBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorBusquedaActionPerformed(evt);
            }
        });

        L_buscar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_buscar.setForeground(new java.awt.Color(255, 255, 255));
        L_buscar.setText("Buscar po:");

        cbCriterioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID del Equipo", "Número de Serie", "Tipo de Equipo", "Marca", "Modelo", "Estado", "Ubicación" }));
        cbCriterioBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCriterioBusquedaActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(13, 40, 74));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID del Equipo", "Número de Serie", "Tipo de Equipo", "Marca", "Modelo", "Estado", "Ubicación"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(13, 40, 74));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        L_buscarEquipos.setFont(new java.awt.Font("HP Simplified", 1, 36)); // NOI18N
        L_buscarEquipos.setForeground(new java.awt.Color(255, 255, 255));
        L_buscarEquipos.setText("Buscar Equipos");

        btnMenu1.setBackground(new java.awt.Color(204, 204, 204));
        btnMenu1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(13, 40, 74));
        btnMenu1.setText("Menu");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(13, 40, 74));
        btnRegresar.setText("Salir");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_logo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_información)
                            .addComponent(L_buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(L_buscarEquipos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMenu1)
                        .addGap(27, 27, 27)
                        .addComponent(btnRegresar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMensajeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(L_logo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(L_buscarEquipos)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(L_información, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu1)
                    .addComponent(btnRegresar))
                .addGap(424, 424, 424))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorBusquedaActionPerformed

    private void cbCriterioBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCriterioBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCriterioBusquedaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String criterio = cbCriterioBusqueda.getSelectedItem().toString();
        String valor = txtValorBusqueda.getText().trim();
        if (valor.isEmpty()) {
            lblMensajeBusqueda.setText("Ingrese un valor para buscar.");
            return;
        }
        // Limpiar resultados anteriores
        listaBuscados.clear();
        modeloTabla.setRowCount(0);
        String columna = "";
        switch (criterio) {
            case "ID del Equipo":
                columna = "id_equipo";
                break;
            case "Número de Serie":
                columna = "numero_serie";
                break;
            case "Tipo de Equipo":
                columna = "t.nombre";
                break;
            case "Marca":
                columna = "Marca";
                break;
            case "Modelo":
                columna = "Modelo";
                break;
            case "Estado":
                columna = "est.descripcion";
                break;
            case "Ubicación":
                columna = "u.nombre";
                break;
        }

        try {
            Connection cn = Conexion.getConexion();
            String sql = "SELECT "
                    + "e.id_equipo, "
                    + "e.numero_serie, "
                    + "t.nombre AS tipo_equipo, "
                    + "e.marca, "
                    + "e.modelo, "
                    + "est.descripcion AS estado, "
                    + "u.nombre AS ubicacion "
                    + "FROM equipos e "
                    + "JOIN cat_tipo_equipo t ON e.id_tipo = t.id_tipo "
                    + "JOIN cat_estado_equipo est ON e.id_estado = est.id_estado "
                    + "JOIN ubicaciones u ON e.id_ubicacion = u.id_ubicacion "
                    + "WHERE " + columna + " LIKE ?";

            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, "%" + valor + "%");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Equipo eq = new Equipo(
                rs.getInt("id_equipo"),
                rs.getString("numero_serie"),
                rs.getString("tipo_equipo"),
                rs.getString("marca"),
                rs.getString("modelo"),
                rs.getString("estado"),
                rs.getString("ubicacion")
                );

                listaBuscados.add(eq);

                modeloTabla.addRow(new Object[]{
                eq.getId(),
                eq.getNumeroSerie(),
                eq.getTipo(),
                eq.getMarca(),
                eq.getModelo(),
                eq.getEstado(),
                eq.getUbicacion()
                });
            }

            if (listaBuscados.isEmpty()) {
                lblMensajeBusqueda.setText("No se encontraron resultados.");
            } else {
                lblMensajeBusqueda.setText("Búsqueda completada.");
            }

            cn.close();

        } catch (SQLException e) {
            lblMensajeBusqueda.setText("Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            listaBuscados.clear();
            modeloTabla.setRowCount(0);
            txtValorBusqueda.setText("");
            lblMensajeBusqueda.setText("Campos limpiados.");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        new menu_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_buscar;
    private javax.swing.JLabel L_buscarEquipos;
    private javax.swing.JLabel L_información;
    private javax.swing.JLabel L_logo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbCriterioBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensajeBusqueda;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtValorBusqueda;
    // End of variables declaration//GEN-END:variables
}
