
package aplicativo_colegio_claretiano;
import java.sql.*;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Luis Daniel
 */
public class Colas extends javax.swing.JFrame {
    Queue<Equipo> colaReparacion = new LinkedList<>();
    DefaultTableModel modeloCola;   

    public Colas() {
        initComponents();
        configurarTabla();
        cargarColaDesdeBD(); 
    }
    private void configurarTabla() {
        modeloCola = new DefaultTableModel(
            new String[]{"ID", "Serie", "Tipo", "Marca", "Modelo", "Estado", "Ubicación"}, 0
        );
        tblColaMantenimiento.setModel(modeloCola);
    }

        
private void cargarColaDesdeBD() {
    colaReparacion.clear();
    modeloCola.setRowCount(0);

    String sql = "SELECT e.id_equipo, e.numero_serie, t.nombre AS tipo_equipo, "
            + "e.marca, e.modelo, est.descripcion AS estado, u.nombre AS ubicacion "
            + "FROM equipos e "
            + "JOIN cat_tipo_equipo t ON e.id_tipo = t.id_tipo "
            + "JOIN cat_estado_equipo est ON e.id_estado = est.id_estado "
            + "JOIN ubicaciones u ON e.id_ubicacion = u.id_ubicacion "
            + "WHERE est.descripcion = 'En reparación'";

    try (Connection cn = Conexion.getConexion();
         PreparedStatement ps = cn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {

            Equipo eq = new Equipo(
                rs.getInt("id_equipo"),
                rs.getString("numero_serie"),
                rs.getString("tipo_equipo"),
                rs.getString("marca"),
                rs.getString("modelo"),
                rs.getString("estado"),
                rs.getString("ubicacion")
            );

            colaReparacion.add(eq);

            modeloCola.addRow(new Object[]{
                eq.getId(),
                eq.getNumeroSerie(),
                eq.getTipo(),
                eq.getMarca(),
                eq.getModelo(),
                eq.getEstado(),
                eq.getUbicacion()
            });
        }

        lblMensaje.setText("Cola cargada correctamente.");

    } catch (SQLException e) {
        lblMensaje.setText("Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L_logo = new javax.swing.JLabel();
        L_siguiente = new javax.swing.JLabel();
        L_mantenimiento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblColaMantenimiento = new javax.swing.JTable();
        L_Ubicacion = new javax.swing.JLabel();
        L_Marca = new javax.swing.JLabel();
        L_Tipo = new javax.swing.JLabel();
        L_numSerie = new javax.swing.JLabel();
        L_Modelo = new javax.swing.JLabel();
        btnAtenderReparacion = new javax.swing.JButton();
        btnVerSiguiente = new javax.swing.JButton();
        btnDarBaja = new javax.swing.JButton();
        btnActualizarCola = new javax.swing.JButton();
        txtSigSerie = new javax.swing.JTextField();
        txtSigTipo = new javax.swing.JTextField();
        txtSigMarca = new javax.swing.JTextField();
        txtSigModelo = new javax.swing.JTextField();
        txtSigUbicacion = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        btnMenu1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 40, 74));

        L_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N

        L_siguiente.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        L_siguiente.setText("Siguiente equipo a atender:");

        L_mantenimiento.setFont(new java.awt.Font("HP Simplified", 1, 36)); // NOI18N
        L_mantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        L_mantenimiento.setText("Mantenimiento de equipos");

        tblColaMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID del Equipo", "Número de Serie", "Tipo de Equipo", "Marca", "Modelo", "Estado", "Ubicación"
            }
        ));
        jScrollPane1.setViewportView(tblColaMantenimiento);

        L_Ubicacion.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_Ubicacion.setForeground(new java.awt.Color(255, 255, 255));
        L_Ubicacion.setText("Ubicación");

        L_Marca.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_Marca.setForeground(new java.awt.Color(255, 255, 255));
        L_Marca.setText("Marca");

        L_Tipo.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_Tipo.setForeground(new java.awt.Color(255, 255, 255));
        L_Tipo.setText("Tipo de equipo");

        L_numSerie.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_numSerie.setForeground(new java.awt.Color(255, 255, 255));
        L_numSerie.setText("Número de serie");

        L_Modelo.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        L_Modelo.setForeground(new java.awt.Color(255, 255, 255));
        L_Modelo.setText("Modelo");

        btnAtenderReparacion.setBackground(new java.awt.Color(204, 204, 204));
        btnAtenderReparacion.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnAtenderReparacion.setForeground(new java.awt.Color(13, 40, 74));
        btnAtenderReparacion.setText("Atender equipo");
        btnAtenderReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderReparacionActionPerformed(evt);
            }
        });

        btnVerSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnVerSiguiente.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnVerSiguiente.setForeground(new java.awt.Color(13, 40, 74));
        btnVerSiguiente.setText("Ver siguiente");
        btnVerSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSiguienteActionPerformed(evt);
            }
        });

        btnDarBaja.setBackground(new java.awt.Color(204, 204, 204));
        btnDarBaja.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnDarBaja.setForeground(new java.awt.Color(13, 40, 74));
        btnDarBaja.setText("Dar de baja equipo");
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });

        btnActualizarCola.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarCola.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnActualizarCola.setForeground(new java.awt.Color(13, 40, 74));
        btnActualizarCola.setText("Actualizar lista");
        btnActualizarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarColaActionPerformed(evt);
            }
        });

        txtSigSerie.setBackground(new java.awt.Color(204, 204, 204));

        txtSigTipo.setBackground(new java.awt.Color(204, 204, 204));

        txtSigMarca.setBackground(new java.awt.Color(204, 204, 204));

        txtSigModelo.setBackground(new java.awt.Color(204, 204, 204));

        txtSigUbicacion.setBackground(new java.awt.Color(204, 204, 204));

        btnMenu1.setBackground(new java.awt.Color(204, 204, 204));
        btnMenu1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(13, 40, 74));
        btnMenu1.setText("Menu");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(13, 40, 74));
        btnRegresar.setText("Salir");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(L_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_numSerie)
                            .addComponent(L_Tipo)
                            .addComponent(L_Marca)
                            .addComponent(L_Modelo)
                            .addComponent(L_Ubicacion))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSigTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSigMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSigModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSigUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSigSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(L_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtenderReparacion)
                        .addGap(49, 49, 49)
                        .addComponent(btnVerSiguiente)
                        .addGap(37, 37, 37)
                        .addComponent(btnDarBaja)
                        .addGap(33, 33, 33)
                        .addComponent(btnActualizarCola))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenu1)
                            .addGap(29, 29, 29)
                            .addComponent(btnRegresar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(L_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L_siguiente)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSigSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_numSerie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSigTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Tipo)))
                    .addComponent(L_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSigMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSigModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Modelo))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSigUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Ubicacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnActualizarCola)
                        .addComponent(btnDarBaja))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerSiguiente)
                        .addComponent(btnAtenderReparacion)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnMenu1))
                        .addGap(19, 19, 19))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarColaActionPerformed
        cargarColaDesdeBD();
    }//GEN-LAST:event_btnActualizarColaActionPerformed

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        if (colaReparacion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cola está vacía");
            return;
        }

        Equipo atendido = colaReparacion.poll();

        try (Connection cn = Conexion.getConexion()) {

            PreparedStatement ps = cn.prepareStatement(
                "UPDATE equipos SET id_estado = 3 WHERE id_equipo = ?"   // 1 = funcional
            );
            ps.setInt(1, atendido.getId());
            ps.executeUpdate();

            lblMensaje.setText("Equipo reparado: " + atendido.getNumeroSerie());

            cargarColaDesdeBD();
            txtSigSerie.setText("");
            txtSigTipo.setText("");
            txtSigMarca.setText("");
            txtSigModelo.setText("");
            txtSigUbicacion.setText("");

        } catch (SQLException e) {
            lblMensaje.setText("Error al atender: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void btnVerSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSiguienteActionPerformed
        if (colaReparacion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cola está vacía");
            return;
        }

        Equipo sig = colaReparacion.peek();

        txtSigSerie.setText(sig.getNumeroSerie());
        txtSigTipo.setText(sig.getTipo());
        txtSigMarca.setText(sig.getMarca());
        txtSigModelo.setText(sig.getModelo());
        txtSigUbicacion.setText(sig.getUbicacion());
    }//GEN-LAST:event_btnVerSiguienteActionPerformed

    private void btnAtenderReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderReparacionActionPerformed
        if (colaReparacion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cola está vacía");
            return;
        }

        Equipo atendido = colaReparacion.poll();

        try (Connection cn = Conexion.getConexion()) {

            PreparedStatement ps = cn.prepareStatement(
                "UPDATE equipos SET id_estado = 1 WHERE id_equipo = ?"   // 1 = funcional
            );
            ps.setInt(1, atendido.getId());
            ps.executeUpdate();

            lblMensaje.setText("Equipo reparado: " + atendido.getNumeroSerie());

            cargarColaDesdeBD();

        } catch (SQLException e) {
            lblMensaje.setText("Error al atender: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAtenderReparacionActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        new menu_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Marca;
    private javax.swing.JLabel L_Modelo;
    private javax.swing.JLabel L_Tipo;
    private javax.swing.JLabel L_Ubicacion;
    private javax.swing.JLabel L_logo;
    private javax.swing.JLabel L_mantenimiento;
    private javax.swing.JLabel L_numSerie;
    private javax.swing.JLabel L_siguiente;
    private javax.swing.JButton btnActualizarCola;
    private javax.swing.JButton btnAtenderReparacion;
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tblColaMantenimiento;
    private javax.swing.JTextField txtSigMarca;
    private javax.swing.JTextField txtSigModelo;
    private javax.swing.JTextField txtSigSerie;
    private javax.swing.JTextField txtSigTipo;
    private javax.swing.JTextField txtSigUbicacion;
    // End of variables declaration//GEN-END:variables
}
