package aplicativo_colegio_claretiano;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Stack;
import javax.swing.JOptionPane;
/**
 *
 * @author Luis Daniel
 */
  
public class Listas_Enlasadas extends javax.swing.JFrame {
private ArrayList<Equipo> listaEquipos = new ArrayList<>();
private Stack<Equipo> pilaEliminados = new Stack<>();
DefaultTableModel modeloTabla;
    /**
     * Creates new form lista
     */
    public Listas_Enlasadas() {
        initComponents();
        modeloTabla = (DefaultTableModel) tblResultados.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        L_mantenimiento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        txtUbicacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCargarBD = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        L_logo = new javax.swing.JLabel();
        btnRestaurarUltimo = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btnMenu1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 40, 74));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID del Equipo", "Número de Serie", "Tipo de Equipo", "Marca", "Modelo", "Estado", "Ubicación"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 770, 220));

        L_mantenimiento.setFont(new java.awt.Font("HP Simplified", 1, 36)); // NOI18N
        L_mantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        L_mantenimiento.setText("Administrar Equipos");
        jPanel1.add(L_mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de Serie:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtSerie.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 109, -1));

        jLabel4.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Equipo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        txtTipo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 109, -1));

        jLabel3.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        txtMarca.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 109, -1));

        jLabel5.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        txtModelo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 109, -1));

        jLabel6.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        cmbEstado.setBackground(new java.awt.Color(204, 204, 204));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operativo", "En reparación", "No disponible", "Dado de baja" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        txtUbicacion.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 160, -1));

        jLabel7.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ubicación:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        btnCargarBD.setBackground(new java.awt.Color(204, 204, 204));
        btnCargarBD.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        btnCargarBD.setForeground(new java.awt.Color(13, 40, 74));
        btnCargarBD.setText("Ver Registros");
        btnCargarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarBDActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 130, 40));

        btnInsertar.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertar.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(13, 40, 74));
        btnInsertar.setText("Registrar Equipo");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 140, 40));

        btnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(13, 40, 74));
        btnEliminar.setText("Eliminar Equipo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 140, 40));

        btnEditar.setBackground(new java.awt.Color(204, 204, 204));
        btnEditar.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(13, 40, 74));
        btnEditar.setText("Editar Equipo");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(13, 40, 74));
        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 140, 40));

        L_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        jPanel1.add(L_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRestaurarUltimo.setBackground(new java.awt.Color(204, 204, 204));
        btnRestaurarUltimo.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        btnRestaurarUltimo.setForeground(new java.awt.Color(13, 40, 74));
        btnRestaurarUltimo.setText("restaurar");
        btnRestaurarUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarUltimoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestaurarUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 130, 40));
        jPanel1.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 420, 20));

        btnMenu1.setBackground(new java.awt.Color(204, 204, 204));
        btnMenu1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(13, 40, 74));
        btnMenu1.setText("Menu");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(13, 40, 74));
        btnRegresar.setText("Salir");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
    listaEquipos.clear();
    modeloTabla.setRowCount(0);
    String numeroSerie = txtSerie.getText().trim();
    String tipoNombre = txtTipo.getText().trim();
    String marca = txtMarca.getText().trim();
    String modelo = txtModelo.getText().trim();
    String estadoNombre = cmbEstado.getSelectedItem().toString();
    String ubicacionNombre = txtUbicacion.getText().trim();

    // Validar campos obligatorios
    if(numeroSerie.isEmpty() || tipoNombre.isEmpty() || marca.isEmpty() ||
       modelo.isEmpty() || estadoNombre.isEmpty() || ubicacionNombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
        return;
    }

    try (Connection cn = Conexion.getConexion()) {

        // ️obtener o crear ID del tipo
        int idTipo = 0;
        PreparedStatement psTipo = cn.prepareStatement(
            "SELECT id_tipo FROM cat_tipo_equipo WHERE nombre = ?"
        );
        psTipo.setString(1, tipoNombre);
        ResultSet rsTipo = psTipo.executeQuery();
        if(rsTipo.next()) {
            idTipo = rsTipo.getInt(1);
        } else {
            PreparedStatement psInsertTipo = cn.prepareStatement(
                "INSERT INTO cat_tipo_equipo(nombre) OUTPUT INSERTED.id_tipo VALUES(?)"
            );
            psInsertTipo.setString(1, tipoNombre);
            ResultSet rsNuevoTipo = psInsertTipo.executeQuery();
            rsNuevoTipo.next();
            idTipo = rsNuevoTipo.getInt(1);
        }

        // Obtener o crear ID del estado
        int idEstado = 0;
        PreparedStatement psEstado = cn.prepareStatement(
            "SELECT id_estado FROM cat_estado_equipo WHERE descripcion = ?"
        );
        psEstado.setString(1, estadoNombre);
        ResultSet rsEstado = psEstado.executeQuery();
        if(rsEstado.next()) {
            idEstado = rsEstado.getInt(1);
        } else {
            PreparedStatement psInsertEstado = cn.prepareStatement(
                "INSERT INTO cat_estado_equipo(descripcion, codigo) OUTPUT INSERTED.id_estado VALUES(?, ?)"
            );
            psInsertEstado.setString(1, estadoNombre);
            psInsertEstado.setString(2, estadoNombre.toUpperCase().replace(" ", "_"));
            ResultSet rsNuevoEstado = psInsertEstado.executeQuery();
            rsNuevoEstado.next();
            idEstado = rsNuevoEstado.getInt(1);
        }

        // Obtener o crear ID de la ubicación
        int idUbicacion = 0;
        PreparedStatement psUbic = cn.prepareStatement(
            "SELECT id_ubicacion FROM ubicaciones WHERE nombre = ?"
        );
        psUbic.setString(1, ubicacionNombre);
        ResultSet rsUbic = psUbic.executeQuery();
        if(rsUbic.next()) {
            idUbicacion = rsUbic.getInt(1);
        } else {
            PreparedStatement psInsertUbic = cn.prepareStatement(
                "INSERT INTO ubicaciones(id_tipo_ubicacion, codigo, nombre) OUTPUT INSERTED.id_ubicacion VALUES(?, ?, ?)"
            );
            psInsertUbic.setInt(1, 5); 
            psInsertUbic.setString(2, ubicacionNombre.toUpperCase().replace(" ", "_"));
            psInsertUbic.setString(3, ubicacionNombre);
            ResultSet rsNuevoUbic = psInsertUbic.executeQuery();
            rsNuevoUbic.next();
            idUbicacion = rsNuevoUbic.getInt(1);
        }

        // Insertar el equipo
        String sqlInsert = "INSERT INTO equipos "
                + "(numero_serie, id_tipo, marca, modelo, id_ubicacion, id_estado, registrado_por) "
                + "OUTPUT INSERTED.id_equipo "
                + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement psInsert = cn.prepareStatement(sqlInsert);
        psInsert.setString(1, numeroSerie);
        psInsert.setInt(2, idTipo);
        psInsert.setString(3, marca);
        psInsert.setString(4, modelo);
        psInsert.setInt(5, idUbicacion);
        psInsert.setInt(6, idEstado);
        psInsert.setInt(7, 1);

        ResultSet rsInsert = psInsert.executeQuery();
        if(rsInsert.next()) {
            int nuevoID = rsInsert.getInt(1);
            JOptionPane.showMessageDialog(this, "Registro insertado. ID: " + nuevoID);
        }

        // Limpiar campos
        txtSerie.setText("");
        txtTipo.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        cmbEstado.setSelectedIndex(0); 
        txtUbicacion.setText("");


    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al insertar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblResultados.getSelectedRow();
        if(fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un equipo para eliminar");
            return;
        }

        // Confirmar eliminación
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el equipo seleccionado?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if(confirm != JOptionPane.YES_OPTION) {
            return; 
        }

        //Obtener ID del equipo
        int idEquipo = (int) modeloTabla.getValueAt(fila, 0); 

        // Eliminar de la base de datos
        try (Connection cn = Conexion.getConexion()) {
            String sql = "DELETE FROM equipos WHERE id_equipo = ?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setInt(1, idEquipo);
            int res = ps.executeUpdate();

            if(res > 0) {
                pilaEliminados.push(listaEquipos.get(fila));
                JOptionPane.showMessageDialog(this, "Equipo eliminado correctamente");

                // Eliminar de la tabla y Listas_Enlasadas
                modeloTabla.removeRow(fila);
                listaEquipos.remove(fila);

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el equipo");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
   int fila = tblResultados.getSelectedRow();
    if(fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un equipo para editar");
        return;
    }

    Equipo eq = listaEquipos.get(fila);

    txtSerie.setText(eq.getNumeroSerie());
    txtTipo.setText(eq.getTipo());
    txtMarca.setText(eq.getMarca());
    txtModelo.setText(eq.getModelo());
    cmbEstado.setSelectedItem(eq.getEstado());
    txtUbicacion.setText(eq.getUbicacion());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCargarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarBDActionPerformed
        listaEquipos.clear();
            modeloTabla.setRowCount(0);
            try (Connection cn = Conexion.getConexion()) {
                String sql = "SELECT "
                        + "e.id_equipo, "
                        + "e.numero_serie, "
                        + "t.nombre AS tipo_equipo, "
                        + "e.marca, "
                        + "e.modelo, "
                        + "est.descripcion AS estado, "
                        + "u.nombre AS ubicacion "
                        + "FROM equipos e "
                        + "JOIN cat_tipo_equipo t ON e.id_tipo = t.id_tipo "
                        + "JOIN cat_estado_equipo est ON e.id_estado = est.id_estado "
                        + "JOIN ubicaciones u ON e.id_ubicacion = u.id_ubicacion";  
                PreparedStatement ps = cn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    Equipo eq = new Equipo(
                    rs.getInt("id_equipo"),
                    rs.getString("numero_serie"),
                    rs.getString("tipo_equipo"),
                    rs.getString("marca"),
                    rs.getString("modelo"),
                    rs.getString("estado"),
                    rs.getString("ubicacion")
                    );
                    listaEquipos.add(eq);
                    modeloTabla.addRow(new Object[]{
                    eq.getId(),
                    eq.getNumeroSerie(),
                    eq.getTipo(),
                    eq.getMarca(),
                    eq.getModelo(),
                    eq.getEstado(),
                    eq.getUbicacion()
                    });
                }
                lblInfo.setText("Datos cargados correctamente.");
            } catch (SQLException e) {
                lblInfo.setText("Error al cargar datos: " + e.getMessage());
            }
    }//GEN-LAST:event_btnCargarBDActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    int fila = tblResultados.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un equipo en la tabla para guardar cambios");
        return;
    }

    // Obtener ID del equipo desde la tabla
    int idEquipo = Integer.parseInt(modeloTabla.getValueAt(fila, 0).toString());

    // Obtener datos desde los campos
    String numeroSerie = txtSerie.getText().trim();
    String tipoNombre = txtTipo.getText().trim();
    String marca = txtMarca.getText().trim();
    String modelo = txtModelo.getText().trim();
    String estadoNombre = cmbEstado.getSelectedItem().toString();
    String ubicacionNombre = txtUbicacion.getText().trim();

    // Validación
    if(numeroSerie.isEmpty() || tipoNombre.isEmpty() || marca.isEmpty() ||
       modelo.isEmpty() || estadoNombre.isEmpty() || ubicacionNombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
        return;
    }

    try (Connection cn = Conexion.getConexion()) {

        // Obtener IDs
        int idTipo = obtenerIdTipo(cn, tipoNombre);
        int idEstado = obtenerIdEstado(cn, estadoNombre);
        int idUbicacion = obtenerIdUbicacion(cn, ubicacionNombre);

        // Actualizar BD
        String sql = "UPDATE equipos SET numero_serie=?, id_tipo=?, marca=?, modelo=?, "
                + "id_ubicacion=?, id_estado=? WHERE id_equipo=?";

        PreparedStatement ps = cn.prepareStatement(sql);
        ps.setString(1, numeroSerie);
        ps.setInt(2, idTipo);
        ps.setString(3, marca);
        ps.setString(4, modelo);
        ps.setInt(5, idUbicacion);
        ps.setInt(6, idEstado);
        ps.setInt(7, idEquipo);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Cambios guardados correctamente");

        // Actualizar lista
        Equipo eq = listaEquipos.get(fila);
        eq.setNumeroSerie(numeroSerie);
        eq.setTipo(tipoNombre);
        eq.setMarca(marca);
        eq.setModelo(modelo);
        eq.setEstado(estadoNombre);
        eq.setUbicacion(ubicacionNombre);

        // Actualizar tabla
        modeloTabla.setValueAt(numeroSerie, fila, 1);
        modeloTabla.setValueAt(tipoNombre, fila, 2);
        modeloTabla.setValueAt(marca, fila, 3);
        modeloTabla.setValueAt(modelo, fila, 4);
        modeloTabla.setValueAt(estadoNombre, fila, 5);
        modeloTabla.setValueAt(ubicacionNombre, fila, 6);

        // Limpiar campos
        txtSerie.setText("");
        txtTipo.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtUbicacion.setText("");
        cmbEstado.setSelectedIndex(0);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRestaurarUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarUltimoActionPerformed
    if (pilaEliminados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay equipos eliminados para restaurar");
        return;
    }

    // POP → último equipo eliminado
    Equipo eq = pilaEliminados.pop();

    try (Connection cn = Conexion.getConexion()) {
        int idTipo = obtenerIdTipo(cn, eq.getTipo());
        int idEstado = obtenerIdEstado(cn, eq.getEstado());
        int idUbicacion = obtenerIdUbicacion(cn, eq.getUbicacion());
        String sql = "INSERT INTO equipos (numero_serie, id_tipo, marca, modelo, id_estado, id_ubicacion, registrado_por) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement ps = cn.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
        ps.setString(1, eq.getNumeroSerie());
        ps.setInt(2, idTipo);
        ps.setString(3, eq.getMarca());
        ps.setString(4, eq.getModelo());
        ps.setInt(5, idEstado);
        ps.setInt(6, idUbicacion);
        ps.setInt(7, 1); 

        ps.executeUpdate();

        // Obtener ID 
        ResultSet rs = ps.getGeneratedKeys();
        int nuevoId = 0;
        if (rs.next()) {
            nuevoId = rs.getInt(1);
        }

         // Construir nuevo objeto Equipo
        Equipo restaurado = new Equipo(
                nuevoId,
                eq.getNumeroSerie(),
                eq.getTipo(),
                eq.getMarca(),
                eq.getModelo(),
                eq.getEstado(),
                eq.getUbicacion()
        );

         //Insertar al INICIO de tu lista enlazada
        listaEquipos.add(0, restaurado);

        //Insertar al INICIO de la tabla
        modeloTabla.insertRow(0, new Object[]{
            restaurado.getId(),
            restaurado.getNumeroSerie(),
            restaurado.getTipo(),
            restaurado.getMarca(),
            restaurado.getModelo(),
            restaurado.getEstado(),
            restaurado.getUbicacion()
        });

        JOptionPane.showMessageDialog(this, "Equipo restaurado correctamente");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al restaurar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRestaurarUltimoActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        new menu_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listas_Enlasadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listas_Enlasadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listas_Enlasadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listas_Enlasadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listas_Enlasadas().setVisible(true);
            }
        });
    }
private int obtenerIdTipo(Connection cn, String tipoNombre) throws SQLException {
    String select = "SELECT id_tipo FROM cat_tipo_equipo WHERE nombre = ?";
    PreparedStatement ps = cn.prepareStatement(select);
    ps.setString(1, tipoNombre);
    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        return rs.getInt(1);
    }

    // Insertar nuevo tipo
    String insert = "INSERT INTO cat_tipo_equipo(nombre) OUTPUT INSERTED.id_tipo VALUES (?)";
    ps = cn.prepareStatement(insert);
    ps.setString(1, tipoNombre);
    ResultSet rsInsert = ps.executeQuery();
    rsInsert.next();
    return rsInsert.getInt(1);
}
private int obtenerIdEstado(Connection cn, String estadoNombre) throws SQLException {
    String select = "SELECT id_estado FROM cat_estado_equipo WHERE descripcion = ?";
    PreparedStatement ps = cn.prepareStatement(select);
    ps.setString(1, estadoNombre);
    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        return rs.getInt(1);
    }

    String codigo = estadoNombre.toUpperCase().replace(" ", "_");

    String insert = "INSERT INTO cat_estado_equipo(descripcion, codigo) "
                  + "OUTPUT INSERTED.id_estado VALUES (?, ?)";
    ps = cn.prepareStatement(insert);
    ps.setString(1, estadoNombre);
    ps.setString(2, codigo);
    ResultSet rsInsert = ps.executeQuery();
    rsInsert.next();
    return rsInsert.getInt(1);
}
private int obtenerIdUbicacion(Connection cn, String ubicacionNombre) throws SQLException {
    String select = "SELECT id_ubicacion FROM ubicaciones WHERE nombre = ?";
    PreparedStatement ps = cn.prepareStatement(select);
    ps.setString(1, ubicacionNombre);
    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        return rs.getInt(1);
    }

    String codigo = ubicacionNombre.toUpperCase().replace(" ", "_");

    String insert = "INSERT INTO ubicaciones(id_tipo_ubicacion, codigo, nombre) "
                  + "OUTPUT INSERTED.id_ubicacion VALUES (?, ?, ?)";
    ps = cn.prepareStatement(insert);
    ps.setInt(1, 5);
    ps.setString(2, codigo);
    ps.setString(3, ubicacionNombre);
    ResultSet rsInsert = ps.executeQuery();
    rsInsert.next();
    return rsInsert.getInt(1);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_logo;
    private javax.swing.JLabel L_mantenimiento;
    private javax.swing.JButton btnCargarBD;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRestaurarUltimo;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
