package aplicativo_colegio_claretiano;

/**
 *
 * @author Luis Daniel
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmbmenu = new javax.swing.JMenuItem();
        jmbsalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmbregistrar = new javax.swing.JMenuItem();
        jmbequipo = new javax.swing.JMenuItem();
        jmbinventario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmbmantenimiento = new javax.swing.JMenuItem();
        jmbreporte = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("INICIO");
        jMenu1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmbmenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jmbmenu.setText("Menú");
        jmbmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbmenuActionPerformed(evt);
            }
        });
        jMenu1.add(jmbmenu);

        jmbsalir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jmbsalir.setText("Salir");
        jmbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbsalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmbsalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("EQUIPOS");
        jMenu2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N

        jmbregistrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jmbregistrar.setText("Registrar Equipos");
        jmbregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbregistrarActionPerformed(evt);
            }
        });
        jMenu2.add(jmbregistrar);

        jmbequipo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jmbequipo.setText("Buscar Equipo");
        jmbequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbequipoActionPerformed(evt);
            }
        });
        jMenu2.add(jmbequipo);

        jmbinventario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jmbinventario.setText("Inventario ");
        jmbinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbinventarioActionPerformed(evt);
            }
        });
        jMenu2.add(jmbinventario);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("SOPORTE");
        jMenu3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jmbmantenimiento.setText("Mantenimiento de Equipos");
        jmbmantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbmantenimientoActionPerformed(evt);
            }
        });
        jMenu3.add(jmbmantenimiento);

        jMenuBar1.add(jMenu3);

        jmbreporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmbreporte.setText("INFORME");
        jmbreporte.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N

        jMenuItem6.setText("Reporte de Equipo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jmbreporte.add(jMenuItem6);

        jMenuBar1.add(jmbreporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jmbsalirActionPerformed

    private void jmbmantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbmantenimientoActionPerformed
        grafos.ir("mantenimiento", this);
    }//GEN-LAST:event_jmbmantenimientoActionPerformed

    private void jmbmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbmenuActionPerformed
        grafos.ir("menu", this);
    }//GEN-LAST:event_jmbmenuActionPerformed

    private void jmbregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbregistrarActionPerformed
        grafos.ir("registrar", this);
    }//GEN-LAST:event_jmbregistrarActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        grafos.ir("reportes", this);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jmbinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbinventarioActionPerformed
        grafos.ir("inventario", this);
    }//GEN-LAST:event_jmbinventarioActionPerformed

    private void jmbequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbequipoActionPerformed
        grafos.ir("equipos", this);
    }//GEN-LAST:event_jmbequipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        grafos.registrar("menu", menu_principal.class);
        grafos.registrar("mantenimiento", Colas.class);
        grafos.registrar("registrar", Listas_Enlasadas.class);
        grafos.registrar("reportes", Reportes.class);
        grafos.registrar("inventario", Ordenamiento.class);
        grafos.registrar("equipos", BusquedaEquipos.class);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jmbequipo;
    private javax.swing.JMenuItem jmbinventario;
    private javax.swing.JMenuItem jmbmantenimiento;
    private javax.swing.JMenuItem jmbmenu;
    private javax.swing.JMenuItem jmbregistrar;
    private javax.swing.JMenu jmbreporte;
    private javax.swing.JMenuItem jmbsalir;
    // End of variables declaration//GEN-END:variables
}
