package aplicativo_colegio_claretiano;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.Comparator;

/**
 *
 * @author Luis Daniel
 */
public class Ordenamiento extends javax.swing.JFrame {
private ArrayList<Equipo> listaEquipos = new ArrayList<>();
DefaultTableModel modeloTabla;
    public Ordenamiento() {
        initComponents();
        modeloTabla = (DefaultTableModel) tablaEquiposOrdenados.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnCargarDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquiposOrdenados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCriterioOrden = new javax.swing.JComboBox<>();
        cbModoOrdenamiento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        L_logo = new javax.swing.JLabel();
        lblMensajeOrdenamiento = new javax.swing.JLabel();
        btnMenu1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 40, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(13, 40, 74));
        btnLimpiar.setText("Limpiar Tabla");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        btnOrdenar.setBackground(new java.awt.Color(204, 204, 204));
        btnOrdenar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(13, 40, 74));
        btnOrdenar.setText("Ordenar Lista");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        btnCargarDatos.setBackground(new java.awt.Color(204, 204, 204));
        btnCargarDatos.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(13, 40, 74));
        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        tablaEquiposOrdenados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID del Equipo", "Número de Serie", "Tipo de Equipo", "Marca", "Modelo", "Estado", "Ubicación"
            }
        ));
        jScrollPane1.setViewportView(tablaEquiposOrdenados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 696, 218));

        jLabel3.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ordenar por:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccionar criterio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        cbCriterioOrden.setBackground(new java.awt.Color(204, 204, 204));
        cbCriterioOrden.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        cbCriterioOrden.setForeground(new java.awt.Color(13, 40, 74));
        cbCriterioOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID del Equipo", "Número de Serie", "Tipo de Equipo", "Modelo", "Marca", "Estado", "Ubicación" }));
        cbCriterioOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCriterioOrdenActionPerformed(evt);
            }
        });
        jPanel1.add(cbCriterioOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        cbModoOrdenamiento.setBackground(new java.awt.Color(204, 204, 204));
        cbModoOrdenamiento.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        cbModoOrdenamiento.setForeground(new java.awt.Color(13, 40, 74));
        cbModoOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));
        cbModoOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModoOrdenamientoActionPerformed(evt);
            }
        });
        jPanel1.add(cbModoOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mostrar Equipos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 260, 60));

        L_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        jPanel1.add(L_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(lblMensajeOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 480, 20));

        btnMenu1.setBackground(new java.awt.Color(204, 204, 204));
        btnMenu1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(13, 40, 74));
        btnMenu1.setText("Menu");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(13, 40, 74));
        btnRegresar.setText("Salir");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbModoOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModoOrdenamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModoOrdenamientoActionPerformed

    private void cbCriterioOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCriterioOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCriterioOrdenActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
    listaEquipos.clear();
    modeloTabla.setRowCount(0);
    try (Connection cn = Conexion.getConexion()) {
        String sql = "SELECT "
                + "e.id_equipo, "
                + "e.numero_serie, "
                + "t.nombre AS tipo_equipo, "
                + "e.marca, "
                + "e.modelo, "
                + "est.descripcion AS estado, "
                + "u.nombre AS ubicacion "
                + "FROM equipos e "
                + "JOIN cat_tipo_equipo t ON e.id_tipo = t.id_tipo "
                + "JOIN cat_estado_equipo est ON e.id_estado = est.id_estado "
                + "JOIN ubicaciones u ON e.id_ubicacion = u.id_ubicacion";  
        PreparedStatement ps = cn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Equipo eq = new Equipo(
            rs.getInt("id_equipo"),
            rs.getString("numero_serie"),
            rs.getString("tipo_equipo"),
            rs.getString("marca"),
            rs.getString("modelo"),
            rs.getString("estado"),
            rs.getString("ubicacion")
            );
            listaEquipos.add(eq);
            modeloTabla.addRow(new Object[]{
            eq.getId(),
            eq.getNumeroSerie(),
            eq.getTipo(),
            eq.getMarca(),
            eq.getModelo(),
            eq.getEstado(),
            eq.getUbicacion()
            });
        }
        lblMensajeOrdenamiento.setText("Datos cargados correctamente.");
    } catch (SQLException e) {
        lblMensajeOrdenamiento.setText("Error al cargar datos: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCargarDatosActionPerformed
    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
    if (listaEquipos.isEmpty()) {
        lblMensajeOrdenamiento.setText("Primero cargue datos desde la BD.");
        return;
    }
    String criterio = cbCriterioOrden.getSelectedItem().toString();
    String modo = cbModoOrdenamiento.getSelectedItem().toString();

    Comparator<Equipo> comparador = null;
    switch (criterio) {
    case "ID del Equipo":
        comparador = Comparator.comparing(Equipo::getId);
        break;
    case "Número de Serie":
        comparador = Comparator.comparing(Equipo::getNumeroSerie);
        break;
    case "Tipo de Equipo":
        comparador = Comparator.comparing(Equipo::getTipo);
        break;
    case "Marca":
        comparador = Comparator.comparing(Equipo::getMarca);
        break;
    case "Modelo":
        comparador = Comparator.comparing(Equipo::getModelo);
        break;
    case "Estado":
        comparador = Comparator.comparing(Equipo::getEstado);
        break;
    case "Ubicación":
        comparador = Comparator.comparing(Equipo::getUbicacion);
        break;
}
    if (modo.equals("Descendente")) {
        comparador = comparador.reversed();
    }

    Collections.sort(listaEquipos, comparador);

    modeloTabla.setRowCount(0);

    for (Equipo eq : listaEquipos) {
        modeloTabla.addRow(new Object[]{
            eq.getId(),
            eq.getNumeroSerie(),
            eq.getTipo(),
            eq.getMarca(),
            eq.getModelo(),
            eq.getEstado(),
            eq.getUbicacion()
            
        });
    }
    lblMensajeOrdenamiento.setText("Lista ordenada correctamente.");       
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    listaEquipos.clear();
    modeloTabla.setRowCount(0);
    lblMensajeOrdenamiento.setText("Tabla limpiada.");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        new menu_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_logo;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbCriterioOrden;
    private javax.swing.JComboBox<String> cbModoOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblMensajeOrdenamiento;
    private javax.swing.JTable tablaEquiposOrdenados;
    // End of variables declaration//GEN-END:variables
}
