package aplicativo_colegio_claretiano;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Daniel
 */
public class Reportes extends javax.swing.JFrame {
    private List<Equipo> listaEquipos;
    
    public Reportes() {
        initComponents();
        cargarEquiposDesdeBD();
    }
    private void cargarEquiposDesdeBD() {
        EquipoDAO dao = new EquipoDAO();
        listaEquipos = dao.obtenerEquipos();
    }

private int contarEquiposRecursivo(List<Equipo> lista, int index) {
    if (index == lista.size()) return 0;
    return 1 + contarEquiposRecursivo(lista, index + 1);
}
private int contarPorMarcaRecursivo(List<Equipo> lista, int index, String marcaBuscada) {
    if (index == lista.size()) return 0;
    int suma = lista.get(index).getMarca().equalsIgnoreCase(marcaBuscada) ? 1 : 0;
    return suma + contarPorMarcaRecursivo(lista, index + 1, marcaBuscada);
}

private int contarPorEstadoRecursivo(List<Equipo> lista, int index, String estadoBuscado) {
    if (index == lista.size()) return 0;
    int suma = lista.get(index).getEstado().equalsIgnoreCase(estadoBuscado) ? 1 : 0;
    return suma + contarPorEstadoRecursivo(lista, index + 1, estadoBuscado);
}
private void generarArchivoTXT() {
    if (listaEquipos == null || listaEquipos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay datos para generar el reporte.");
        return;
    }

    String marcaBuscada = txtMarcaBuscar.getText().trim();
    List<Equipo> listaFiltrada;

    if (!marcaBuscada.isEmpty()) {
        listaFiltrada = listaEquipos.stream()
                .filter(e -> e.getMarca().equalsIgnoreCase(marcaBuscada))
                .toList();
    } else {
        listaFiltrada = listaEquipos;
    }

    int total = contarEquiposRecursivo(listaFiltrada, 0);
    int operativos = contarPorEstadoRecursivo(listaFiltrada, 0, "Operativo");
    int dadosBaja = contarPorEstadoRecursivo(listaFiltrada, 0, "Dado de baja");

    String ruta = System.getProperty("user.home") + "\\Desktop\\Reporte_Equipos.txt";

    try (PrintWriter writer = new PrintWriter(new FileWriter(ruta))) {

        writer.println("=======================================");
        writer.println("           REPORTE DE EQUIPOS          ");
        writer.println("=======================================");
        writer.println("Fecha: " + java.time.LocalDateTime.now());
        writer.println("---------------------------------------");
        writer.println("Total de Equipos: " + total);
        writer.println("Operativos: " + operativos);
        writer.println("Dado de Baja: " + dadosBaja);
        writer.println("---------------------------------------");

        if (!marcaBuscada.isEmpty()) {
            int totalMarca = contarPorMarcaRecursivo(listaFiltrada, 0, marcaBuscada);
            writer.println("Equipos de la marca '" + marcaBuscada + "': " + totalMarca);
            writer.println("---------------------------------------");
        }

        writer.println("\nLISTA DETALLADA:\n");

        for (Equipo e : listaFiltrada) {
            writer.println("ID: " + e.getId());
            writer.println("Número Serie: " + e.getNumeroSerie());
            writer.println("Tipo: " + e.getTipo());
            writer.println("Marca: " + e.getMarca());
            writer.println("Modelo: " + e.getModelo());
            writer.println("Estado: " + e.getEstado());
            writer.println("Ubicación: " + e.getUbicacion());
            writer.println("---------------------------------------");
        }

        JOptionPane.showMessageDialog(this, 
                "Reporte generado correctamente en:\n" + ruta);

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, 
                "Error al generar archivo: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        L_logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMarcaBuscar = new javax.swing.JTextField();
        txtOperativos = new javax.swing.JTextField();
        txtInoperativos = new javax.swing.JTextField();
        txtResultadoMarca = new javax.swing.JTextField();
        txtTotalEquipos = new javax.swing.JTextField();
        btnVerRegistro = new javax.swing.JButton();
        btnGenerarTXT = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 40, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Control de Inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        L_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        jPanel1.add(L_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar equipos por marca:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Equipos Operativos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Equipos dado de baja:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total por marca:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total de Equipos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        txtMarcaBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtMarcaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtMarcaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 170, 30));

        txtOperativos.setEditable(false);
        txtOperativos.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtOperativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 170, 30));

        txtInoperativos.setEditable(false);
        txtInoperativos.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtInoperativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 170, 30));

        txtResultadoMarca.setEditable(false);
        txtResultadoMarca.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtResultadoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 170, 30));

        txtTotalEquipos.setEditable(false);
        txtTotalEquipos.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtTotalEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 170, 30));

        btnVerRegistro.setBackground(new java.awt.Color(204, 204, 204));
        btnVerRegistro.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnVerRegistro.setForeground(new java.awt.Color(13, 40, 74));
        btnVerRegistro.setText("Ver registro");
        btnVerRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        btnGenerarTXT.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerarTXT.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnGenerarTXT.setForeground(new java.awt.Color(13, 40, 74));
        btnGenerarTXT.setText("Generar Reporte");
        btnGenerarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTXTActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(13, 40, 74));
        btnRegresar.setText("Salir");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        btnMenu1.setBackground(new java.awt.Color(204, 204, 204));
        btnMenu1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(13, 40, 74));
        btnMenu1.setText("Menu");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaBuscarActionPerformed

    private void btnGenerarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTXTActionPerformed
        generarArchivoTXT();
    }//GEN-LAST:event_btnGenerarTXTActionPerformed

    private void btnVerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegistroActionPerformed
                                                
    if (listaEquipos == null || listaEquipos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay equipos cargados.");
        return;
    }

    String marca = txtMarcaBuscar.getText().trim();
    List<Equipo> listaFiltrada;

    if (!marca.isEmpty()) {
        listaFiltrada = listaEquipos.stream()
                .filter(e -> e.getMarca().equalsIgnoreCase(marca))
                .toList();
    } else {
        listaFiltrada = listaEquipos;  
    }

    int total = contarEquiposRecursivo(listaFiltrada, 0);
    txtTotalEquipos.setText(String.valueOf(total));

    int operativos = contarPorEstadoRecursivo(listaFiltrada, 0, "Operativo");
    txtOperativos.setText(String.valueOf(operativos));

    int inoperativos = contarPorEstadoRecursivo(listaFiltrada, 0, "Dado de baja");
    txtInoperativos.setText(String.valueOf(inoperativos));

    if (!marca.isEmpty()) {
        txtResultadoMarca.setText(String.valueOf(total)); 
    } else {
        txtResultadoMarca.setText("0");
    }

    JOptionPane.showMessageDialog(this, "Registro generado");
    }//GEN-LAST:event_btnVerRegistroActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        new menu_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_logo;
    private javax.swing.JButton btnGenerarTXT;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInoperativos;
    private javax.swing.JTextField txtMarcaBuscar;
    private javax.swing.JTextField txtOperativos;
    private javax.swing.JTextField txtResultadoMarca;
    private javax.swing.JTextField txtTotalEquipos;
    // End of variables declaration//GEN-END:variables
}
